/*
 * DỮ LIỆU PORTFOLIO — sửa nội dung ở file này.
 *
 * Mỗi dự án (items) có:
 *   id        trùng tên file trong assets/video/ (<id>.mp4, <id>-loop.mp4, <id>.jpg)
 *   dept      mã mục (lv, sv, nw, fd, br, led) — xem `departments`
 *   orient    "v" (dọc 9:16) hoặc "h" (ngang); ratio: tỉ lệ khung nếu không phải 16:9
 *   featured  true = có trang riêng; còn lại được xếp vào trang danh sách (3–4 dự án/trang)
 *   stats     5 chỉ số 0–100: [Nhịp dựng, Màu sắc, Motion, Âm thanh, Kể chuyện]
 *   youtube   (tuỳ chọn) link YouTube/Drive — nếu có sẽ hiện thêm nút mở link
 */
window.CATALOGUE = {
  profile: {
    name: "Đoàn Ngọc Long",
    role: "Video Editor · Motion Designer · Graphic Designer",
    city: "Đà Nẵng",
    hometown: "Phú Vang, Huế",
    email: "jlevernet123@gmail.com",
    phone: "0392 289 295",
    portrait: "assets/img/portrait.jpg",
    bio: [
      "Tôi là Đoàn Ngọc Long, video editor và motion designer ở Đà Nẵng. Từ năm 2022 tôi làm việc với kênh YouTube, đài truyền hình, agency và chủ đầu tư bất động sản, ở đủ định dạng: video dài, talking head, short video, tin tức, show ẩm thực, phim thương hiệu và visual LED sân khấu.",
      "Tôi thích những video có nhịp rõ ràng, hình ảnh sạch và đồ hoạ phục vụ câu chuyện. Dự án nào tôi cũng cố gắng để người xem ở lại đến giây cuối.",
    ],
    languages: "Tiếng Việt · English",
    interests: "Motion graphic · Animation · Làm phim · Thiết kế đồ hoạ",
    softSkills: ["Giao tiếp", "Sáng tạo", "Làm việc nhóm", "Tổ chức", "Dẫn dắt"],
  },

  // Mốc thời gian tính từ video đầu tiên đến video cuối cùng của từng khách hàng, mới nhất trước
  record: [
    { when: "09 — 10/2026", what: "VTV8", where: "Series Vietnam Travel và Vietnam News dạng dọc, phụ đề tiếng Anh, nhiều tập mỗi tuần" },
    { when: "09 — 10/2026", what: "Sofa TV", where: "Video dài về huyền thoại bóng đá: dựng tư liệu, hiệu ứng TV cổ, kể chuyện bằng hình" },
    { when: "06 — 10/2026", what: "VTC", where: "Show review ẩm thực dọc ở Hà Nội và Hải Phòng, hơn 20 tập" },
    { when: "04 — 10/2026", what: "DaPixel Agency", where: "Reel nhà hàng và nghệ sĩ: Manzoku, KKokio, QQ, EI, Quá Ông Sáu" },
    { when: "04 — 09/2026", what: "Onbeat", where: "Review quán ăn, video KOL, teaser nghệ sĩ" },
    { when: "02 — 09/2026", what: "IMUNDEX", where: "Series hơn 100 video sản phẩm nội thất, phụ đề tiếng Anh" },
    { when: "02 — 04/2026", what: "Bravo", where: "TVC bất động sản Vĩnh Hưng, video Tết, video sự kiện" },
    { when: "12/2025 — 07/2026", what: "Regal Group", where: "Teaser sự kiện, video KOL, phim sản phẩm, tiến độ dự án, visual LED kick-off" },
    { when: "12/2024 — 09/2026", what: "Kênh YouTube Lợi Trần", where: "Video dài talking head kết hợp minh hoạ và motion graphic, video ngắn" },
    { when: "06/2023 — 09/2025", what: "Visual LED sân khấu", where: "Đêm nhạc Mứt Gừng, TPP, OCB, Vietravel" },
    { when: "2023 — 08/2025", what: "Kênh YouTube Vui Vẻ", where: "Video dài “Tất cả…” và series “Đơn giản hoá” cho kênh 1,25 triệu người đăng ký, kèm quảng cáo lồng ghép" },
    { when: "04/2024 — 01/2025", what: "Focus Event", where: "TVC Queen Kara, recap Big Bang Club, video quảng cáo karaoke và sự kiện" },
    { when: "05/2023 — 04/2025", what: "Kênh YouTube Teakill", where: "Hoạt hình giải thích khoa học, bảng xếp hạng, meme review" },
    { when: "11/2022 — 04/2023", what: "N2L Entertainment", where: "Video Editor & Graphic Designer: quản lý dự án video thế giới động vật kết hợp motion graphic" },
    { when: "09 — 10/2022", what: "Wemo Media", where: "Video Editor: hiệu ứng âm thanh, lồng tiếng phim hoạt hình" },
    { when: "2019 — 2021", what: "Câu lạc bộ sinh viên", where: "NYS Club, FTV Club, BaoLinh Project: dựng video và thiết kế" },
  ],
  education: [
    { when: "Quạ HD", what: "Dựng phim & làm phim · Motion graphic & animation", where: "Các khoá dựng video YouTube, làm phim và chuyển động" },
    { when: "ĐH FPT Đà Nẵng", what: "Graphic Design & Advertising · UX/UI Design", where: "Khởi đầu từ ngành Kỹ thuật phần mềm (2018)" },
  ],
  software: {
    main: ["Premiere Pro", "After Effects", "Photoshop"],
    more: ["Illustrator", "DaVinci Resolve", "Lightroom", "Blender", "Figma"],
  },

  departments: [
    {
      key: "lv", no: "I", name: "Long Video", sub: "Talking head · Kể chuyện · YouTube",
      intro: "Video dài 8–12 phút cho kênh YouTube Lợi Trần. Người dẫn kể chuyện trước phông xanh, phía sau là bối cảnh minh hoạ, tư liệu và motion graphic giải thích từng ý.",
      note: "Dựng hoàn chỉnh từ footage thô: cắt nhịp lời thoại, ghép phông, minh hoạ, âm thanh và phụ đề.",
    },
    {
      key: "fn", no: "II", name: "Animation & Fun", sub: "Hoạt hình · Giải trí · YouTube",
      intro: "Video dài vui nhộn 5–25 phút: giải trí kiến thức, hoạt hình giải thích khoa học, bảng xếp hạng, phim hoạt hình châm biếm và vlog. Nhân vật minh hoạ, meme và hiệu ứng âm thanh đặt đúng nhịp để người xem bật cười.",
      note: "Kênh Vui Vẻ (1,25 triệu người đăng ký), kênh Teakill, phim hoạt hình Trường thôn, kênh PHT và vlog Nghịch.",
    },
    {
      key: "rv", no: "III", name: "Reaction & Review", sub: "Review phim · Reaction · YouTube",
      intro: "Video review phim và reaction: người dẫn bình luận, cảnh phim cắt đúng câu đùa, meme và hiệu ứng âm thanh dồn dập để người xem cười liên tục.",
      note: "Series review phim cho kênh Batman Tuyệt Đối và video reaction.",
    },
    {
      key: "sv", no: "IV", name: "Short Video", sub: "Reels · TikTok · Shorts",
      intro: "Video dọc dưới hai phút cho nghệ sĩ, nhà hàng và thương hiệu. Hook trong ba giây đầu, nhịp cắt theo nhạc, chữ đặt đúng vùng an toàn của từng nền tảng.",
      note: "Bao gồm cả series dài hơi như hơn 100 video sản phẩm cho IMUNDEX.",
    },
    {
      key: "br", no: "V", name: "Brand Film", sub: "Bất động sản · Sản phẩm · TVC",
      intro: "Teaser sự kiện, video KOL, phim sản phẩm, TVC và highlight dự án. Xuất bản đến 4K, màu được cân thống nhất cho cả chiến dịch.",
      note: "Regal Group, Kohler, Mizuki Park, Bravo, Focus Event.",
    },
    {
      key: "led", no: "VI", name: "LED Visual", sub: "Sân khấu · Ca nhạc",
      intro: "Visual cho màn LED chính của sân khấu ca nhạc, thiết kế và chuyển động khớp từng đoạn của bài hát.",
      note: "Visual sân khấu cho QQ, bộ visual đêm nhạc Mứt Gừng, sự kiện OCB và Vietravel 2024.",
    },
    {
      key: "fd", no: "VII", name: "Food Review", sub: "Show ẩm thực VTC",
      intro: "Show review ẩm thực dạng dọc 2–4 phút. Người dẫn đi ăn, phản ứng thật, phụ đề rõ và cận cảnh món ăn đúng lúc.",
      note: "Hơn 20 tập ở Hà Nội và Hải Phòng: bún, bánh cuốn, phở, ốc, tôm hùm…",
    },
    {
      key: "nw", no: "VIII", name: "News & Travel", sub: "Series truyền hình VTV8",
      intro: "Tin tức và du lịch dạng dọc cho VTV8, phụ đề tiếng Anh dành cho khán giả quốc tế.",
      note: "Vietnam Travel và Vietnam News.",
    },
  ],

  items: [
    /* ───────────── I. LONG VIDEO ───────────── */
    {
      id: "lv1", dept: "lv", orient: "h", featured: true,
      title: "Lợi Trần · Bác sĩ trung cổ", client: "Kênh YouTube Lợi Trần", year: "09/2026", duration: "10:12",
      role: "Dựng & motion graphic", tools: ["Premiere Pro", "After Effects"],
      headline: "Bác sĩ thời trung cổ chữa bệnh thế nào?",
      lead: "Mười phút kể chuyện về y học thời trung cổ, từ cây gậy thần Asclepius đến chiếc mặt nạ mỏ chim của bác sĩ dịch hạch.",
      sections: [
        { h: "Talking head kết hợp minh hoạ", p: "Người dẫn quay trước phông xanh, được ghép vào phòng làm việc vẽ tay. Mỗi khái niệm có một tấm minh hoạ hoặc biểu tượng chuyển động đi kèm." },
        { h: "Giữ nhịp cho video dài", p: "Cắt sát lời thoại, đổi khung hình liên tục, chèn tư liệu đúng lúc để người xem không rời mắt trong suốt mười phút." },
      ],
      panel: "Video dài 10 phút: talking head ghép phông minh hoạ, motion graphic giải thích.",
      stats: [88, 80, 86, 82, 92],
    },
    {
      id: "lv2", dept: "lv", orient: "h", featured: true,
      title: "Lợi Trần · Ăn máy bay", client: "Kênh YouTube Lợi Trần", year: "08/2026", duration: "8:43",
      role: "Dựng & motion graphic", tools: ["Premiere Pro", "After Effects"],
      headline: "Người đàn ông ăn cả một chiếc máy bay",
      lead: "Câu chuyện có thật về người đàn ông ăn xe đạp, bóng đèn và cả một chiếc máy bay, được kể lại bằng tư liệu, phim cũ và đồ hoạ.",
      sections: [
        { h: "Dựng từ tư liệu", p: "Phim tài liệu, ảnh cũ và cảnh quay mô phỏng được xử lý màu như thước phim xưa, xen kẽ với phần dẫn chuyện." },
        { h: "Đồ hoạ trên nền giấy", p: "Số liệu và mốc thời gian được trình bày trên nền giấy kraft, giữ chung một phong cách với cả video." },
      ],
      panel: "Video dài 8 phút: phim tư liệu, xử lý màu phim cũ, đồ hoạ nền giấy.",
      stats: [85, 84, 80, 80, 90],
    },
    {
      id: "lv3", dept: "lv", orient: "h",
      title: "Lợi Trần · Đại dương", client: "Kênh YouTube Lợi Trần", year: "07/2026", duration: "11:27",
      role: "Dựng & motion graphic", tools: ["Premiere Pro", "After Effects"],
      headline: "Những sinh vật kỳ lạ dưới đáy đại dương",
      lead: "Rồng biển lá, cá mắt thùng và những loài sống ở vùng biển sâu. Người dẫn đứng trước tấm bảng chiếu trong một lớp học vẽ tay.",
      sections: [
        { h: "Một lớp học hoạt hình", p: "Bối cảnh lớp học minh hoạ với màn chiếu, kệ sách và micro. Hình ảnh sinh vật xuất hiện trên màn chiếu theo lời giảng." },
        { h: "Hoạt hình xen kẽ", p: "Những đoạn hoạt hình nét vẽ tay minh hoạ các ý trừu tượng và tạo nhịp nghỉ cho video hơn mười phút." },
      ],
      panel: "Video dài 11 phút: bối cảnh lớp học minh hoạ, hoạt hình nét vẽ tay.",
      stats: [84, 82, 88, 80, 90],
    },
    {
      id: "lv4", dept: "lv", orient: "h",
      title: "Sofa TV · Huyền thoại bóng đá", client: "Sofa TV", year: "10/2026", duration: "9:57",
      role: "Dựng & hiệu ứng", tools: ["Premiere Pro", "After Effects"],
      panel: "Video dài 10 phút về Pelé và Maradona: tư liệu đen trắng, hiệu ứng màn hình TV cổ, nhịp kể chuyện.",
      stats: [82, 84, 74, 82, 88],
    },

    {
      id: "th1", dept: "lv", orient: "h",
      title: "Demo bình luận · Nước Mỹ có đang sụp đổ?", client: "Demo kênh bình luận", year: "05/2025", duration: "0:56",
      role: "Dựng & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Demo video bình luận chính trị: tư liệu tin tức, ảnh chụp bài báo, bảng điều tra 3D và motion graphic bóng người.",
      stats: [84, 82, 90, 80, 86],
    },
    {
      id: "th2", dept: "lv", orient: "h",
      title: "Demo bình luận · Thuế quan của Trump", client: "Demo kênh bình luận", year: "05/2025", duration: "0:30",
      role: "Dựng & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Demo 30 giây: tin tức thuế quan, bảng điều tra và cảnh dựng điện ảnh cho kênh bình luận.",
      stats: [86, 80, 86, 80, 82],
    },
    /* ───────────── II. ANIMATION & FUN ───────────── */
    /* Kênh Vui Vẻ (2023 – 2025): video đăng trên YouTube, xem bằng trình phát nhúng */
    {
      id: "vv1", dept: "fn", orient: "h", featured: true, yt: "fnTfJ130mjw", views: 3951854,
      gallery: ["vv2", "vv3", "vv4"],
      channel: [["1,25 triệu", "Người đăng ký"], ["38+", "Video tôi dựng · 2023–2025"], ["40 triệu+", "Lượt xem các video đó"]],
      title: "Vui Vẻ · Trend đần độn nhất mạng xã hội", client: "Kênh YouTube Vui Vẻ", year: "08/2024", duration: "15:11",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects", "Photoshop"],
      headline: "Kênh Vui Vẻ: hơn 40 triệu lượt xem",
      lead: "Từ 2023 đến 2025 tôi dựng các video dài “Tất cả…” và series “Đơn giản hoá” cho Vui Vẻ, kênh giải trí kiến thức hơn 1,25 triệu người đăng ký. Đây là dự án tôi gắn bó lâu và có nhiều kỷ niệm nhất.",
      sections: [
        { h: "Cả một chủ đề trong 15 phút", p: "Minh hoạ, meme và âm thanh đặt đúng nhịp kể của người dẫn, để những chủ đề dài vẫn vui và dễ hiểu. Kèm các đoạn quảng cáo lồng ghép cho Samsung Galaxy, OPPO, Tecno, Odoo, Prep và Viettel Money." },
      ],
      panel: "Video dài 15 phút, 3,9 triệu lượt xem: tổng hợp trend mạng xã hội bằng minh hoạ, meme và motion graphic.",
      stats: [88, 80, 88, 90, 92],
    },
    {
      id: "vv2", dept: "fn", orient: "h", yt: "wQaS39Otf3k", views: 3206981, hidden: true,
      title: "Vui Vẻ · Tất cả các mạng xã hội", client: "Kênh YouTube Vui Vẻ", year: "09/2024", duration: "17:39",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Lịch sử và tính cách của từng mạng xã hội trong 17 phút.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv3", dept: "fn", orient: "h", yt: "n-L0TQr-obI", views: 2476195, hidden: true,
      title: "Vui Vẻ · Việc làm thêm thời sinh viên", client: "Kênh YouTube Vui Vẻ", year: "04/2025", duration: "13:57",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Tất cả các việc làm thêm thời sinh viên, kể bằng minh hoạ và meme.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv4", dept: "fn", orient: "h", yt: "XuVMxSIwV1g", views: 2246074, hidden: true,
      title: "Vui Vẻ · Kỹ năng cho sinh viên", client: "Kênh YouTube Vui Vẻ", year: "12/2024", duration: "18:42",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Những kỹ năng cần thiết cho sinh viên trong 18 phút.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv5", dept: "fn", orient: "h", yt: "cMCM4jgpv8g", views: 1844289,
      title: "Vui Vẻ · Drama showbiz Việt", client: "Kênh YouTube Vui Vẻ", year: "08/2024", duration: "10:50",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 11 phút, 1,8 triệu lượt xem: tổng hợp drama showbiz Việt bằng tư liệu, meme và minh hoạ.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv6", dept: "fn", orient: "h", yt: "AxwxYxYUhlI", views: 1713543,
      title: "Vui Vẻ · Bảo bối bựa của Doraemon", client: "Kênh YouTube Vui Vẻ", year: "08/2025", duration: "18:43",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 19 phút, 1,7 triệu lượt xem: những bảo bối bựa nhất của Doraemon, dựng như một cuốn catalogue bảo bối.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv7", dept: "fn", orient: "h", yt: "aoNquxbLpqA", views: 1733426,
      title: "Vui Vẻ · Những tên tội phạm đần nhất", client: "Kênh YouTube Vui Vẻ", year: "03/2025", duration: "12:22",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 12 phút, 1,7 triệu lượt xem: những vụ phạm tội ngớ ngẩn nhất, kể bằng hoạt hình và meme.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv8", dept: "fn", orient: "h", yt: "gmotjPrwr64", views: 1700476,
      title: "Vui Vẻ · Truyền thuyết đô thị có thật", client: "Kênh YouTube Vui Vẻ", year: "03/2025", duration: "14:23",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 14 phút, 1,7 triệu lượt xem: truyền thuyết đô thị với không khí rùng rợn mà vẫn hài hước.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv9", dept: "fn", orient: "h", yt: "v_RJcMVRvxg", views: 1655891,
      title: "Vui Vẻ · Người nổi tiếng từng đi tù (P2)", client: "Kênh YouTube Vui Vẻ", year: "08/2025", duration: "14:19",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 14 phút, 1,6 triệu lượt xem: phần 2 của series người nổi tiếng từng ngồi tù.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv10", dept: "fn", orient: "h", yt: "X9TgskZXKf8", views: 1583689,
      title: "Vui Vẻ · Tất cả các tà giáo", client: "Kênh YouTube Vui Vẻ", year: "12/2024", duration: "15:02",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 15 phút, 1,6 triệu lượt xem: các tà giáo nổi tiếng thế giới, dựng nhịp nhanh với tư liệu và minh hoạ.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv11", dept: "fn", orient: "h", yt: "_eE2Cn0NbI8", views: 1548053,
      title: "Vui Vẻ · Các đời tổng thống Mỹ", client: "Kênh YouTube Vui Vẻ", year: "10/2024", duration: "25:08",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 25 phút, 1,5 triệu lượt xem: tất cả các đời tổng thống Mỹ, mỗi người một đoạn minh hoạ riêng.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "vv12", dept: "fn", orient: "h", yt: "QICWDoSEklM", views: 1591905,
      title: "Vui Vẻ · Truyện ngắn sách giáo khoa", client: "Kênh YouTube Vui Vẻ", year: "05/2025", duration: "15:05",
      role: "Dựng phim & motion graphic", tools: ["Premiere Pro", "After Effects"],
      panel: "Video 15 phút, 1,6 triệu lượt xem: tóm tắt các truyện ngắn trong sách giáo khoa văn học.",
      stats: [84, 80, 88, 86, 90],
    },
    {
      id: "fn1", dept: "fn", orient: "h", featured: true,
      title: "Teakill · Bảng xếp hạng động vật", client: "Kênh YouTube Teakill", year: "03/2024", duration: "8:31",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro", "Photoshop"],
      headline: "Xếp hạng từ “xước nhẹ” đến “ăn tử”",
      lead: "Video hoạt hình tám phút xếp hạng mức độ nguy hiểm khi đối đầu với các loài động vật. Nhân vật áo hoodie xanh dẫn chuyện, bảng xếp hạng màu sắc và meme xuất hiện đúng nhịp.",
      sections: [
        { h: "Nhân vật dẫn chuyện", p: "Một nhân vật hoạt hình xuyên suốt kênh, biểu cảm theo từng câu thoại. Nền giấy kẻ ô, bảng đen và tư liệu thật được ghép lẫn với nhau." },
        { h: "Hài đúng nhịp", p: "Âm thanh, zoom nhanh, freeze frame và chữ chèn được canh theo từng câu đùa để giữ người xem cười suốt video." },
      ],
      panel: "Hoạt hình giải thích 8 phút: nhân vật dẫn chuyện, bảng xếp hạng, meme đúng nhịp.",
      stats: [90, 86, 90, 88, 92],
    },
    {
      id: "fn2", dept: "fn", orient: "h", featured: true,
      title: "Trường thôn · Ngưng phán xét", client: "Hoạt hình châm biếm", year: "07/2024", duration: "9:41",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro", "Photoshop"],
      headline: "Ngưng phán xét",
      lead: "Phim hoạt hình bình luận gần mười phút với nhân vật biếm hoạ đội mũ cối. Nền giấy nhàu, ảnh cắt dán và chuyển động kiểu stop-motion tạo cảm giác vui và gần gũi.",
      sections: [
        { h: "Biếm hoạ chuyển động", p: "Nhân vật được rig để cử động tay, đầu và biểu cảm. Nhiều phiên bản nhân vật xuất hiện cùng lúc để diễn tả các luồng ý kiến." },
        { h: "Cắt dán trên nền giấy", p: "Ảnh tư liệu, meme và chữ tiêu đề được cắt dán lên nền giấy, giữ một phong cách thống nhất cho cả series." },
      ],
      panel: "Hoạt hình bình luận 10 phút: biếm hoạ chuyển động, cắt dán trên nền giấy.",
      stats: [84, 80, 88, 82, 90],
    },
    {
      id: "fn3", dept: "fn", orient: "h", featured: true,
      title: "Teakill · Nếu Trái Đất ngừng quay", client: "Kênh YouTube Teakill", year: "07/2023", duration: "5:37",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      headline: "Nếu Trái Đất ngừng quay?",
      lead: "Một câu hỏi giả tưởng được trả lời bằng hoạt hình: gió giật 470 m/s, đại dương dồn về hai cực và nhân vật áo hoodie xanh bị thổi bay khỏi nóc nhà.",
      sections: [
        { h: "Khoa học dễ hiểu", p: "Mỗi hệ quả được minh hoạ bằng một cảnh riêng: bản đồ, ảnh vệ tinh, phòng học, thành phố. Số liệu hiện lên to và rõ để người xem nhớ lâu." },
        { h: "Giữ chất vui của kênh", p: "Biểu cảm phóng đại, hiệu ứng âm thanh và những câu thoại bất ngờ giúp một chủ đề khoa học trở nên nhẹ nhàng." },
      ],
      panel: "Hoạt hình giả tưởng khoa học: Trái Đất ngừng quay, nhân vật bị thổi bay khỏi toà nhà.",
      stats: [88, 86, 88, 86, 90],
    },
    {
      id: "fn4", dept: "fn", orient: "h",
      title: "Teakill · Rung chấn ngoài đời thật", client: "Kênh YouTube Teakill", year: "05/2023", duration: "9:25",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      panel: "Phân tích “Rung chấn” trong Attack on Titan nếu xảy ra ngoài đời: bản đồ, manga và mô phỏng.",
      stats: [86, 84, 86, 84, 90],
    },
    {
      id: "fn5", dept: "fn", orient: "h",
      title: "Teakill · Phóng xạ", client: "Kênh YouTube Teakill", year: "09/2023", duration: "9:00",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      panel: "Hoạt hình kể về phóng xạ và uranium, xen kẽ tư liệu lịch sử và nhân vật hài hước.",
      stats: [84, 84, 86, 84, 88],
    },
    {
      id: "fn6", dept: "fn", orient: "h",
      title: "Teakill · Một đất nước", client: "Kênh YouTube Teakill", year: "12/2023", duration: "5:10",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      panel: "Hoạt hình giả tưởng vui nhộn với nhân vật dẫn chuyện, mô hình 3D và hiệu ứng TV cổ.",
      stats: [86, 86, 86, 84, 86],
    },
    {
      id: "fn7", dept: "fn", orient: "h",
      title: "Teakill · 5 cách", client: "Kênh YouTube Teakill", year: "05/2024", duration: "6:17",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      panel: "Hoạt hình khoa học vui: vũ trụ, toán học và những nhân vật biểu cảm phóng đại.",
      stats: [86, 86, 86, 84, 86],
    },
    {
      id: "fn8", dept: "fn", orient: "h",
      title: "PHT · Người nằm trong bụng cá voi", client: "Kênh YouTube PHT", year: "03/2023", duration: "9:09",
      role: "Dựng & motion graphic", tools: ["After Effects", "Premiere Pro"],
      panel: "Video giải thích có thật hay không chuyện người sống sót trong bụng cá voi: HUD, số liệu, mô phỏng 3D.",
      stats: [82, 86, 88, 80, 86],
    },
    {
      id: "fn9", dept: "fn", orient: "h", ratio: "4/3",
      title: "Nghịch · Đi biển", client: "Nghịch", year: "02/2026", duration: "1:37",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      panel: "Vlog đi biển cùng nhóm bạn: chữ chèn vui, màu nắng ấm, phụ đề song ngữ.",
      stats: [84, 88, 60, 80, 80],
    },

    /* ───────────── III. REACTION & REVIEW ───────────── */
    {
      id: "bm1", dept: "rv", orient: "h", featured: true, yt: "3BvXAp7U3cg", views: 559023,
      gallery: ["bm2", "bm3", "bm4"],
      channel: [["80,6 nghìn", "Người đăng ký"], ["4", "Video tôi dựng · 02–03/2026"], ["1,3 triệu", "Lượt xem các video đó"]],
      title: "Batman Tuyệt Đối · Bạch Tuyết", client: "Kênh YouTube Batman Tuyệt Đối", year: "03/2026", duration: "26:05",
      role: "Dựng video review", tools: ["Premiere Pro", "After Effects"],
      headline: "Tôi xem phim rác vì biết nó rác",
      lead: "Series review phim dở cho kênh Batman Tuyệt Đối: người dẫn vừa xem vừa “chê”, cảnh phim cắt đúng câu đùa, meme và hiệu ứng âm thanh chen vào đúng lúc.",
      sections: [
        { h: "Giữ nhịp cười suốt 20 phút", p: "Lời bình, cảnh phim và chữ chú thích đan xen liên tục, mỗi đoạn có một điểm nhấn để người xem không bấm sang video khác." },
      ],
      panel: "Video review 26 phút, 559 nghìn lượt xem: Bạch Tuyết live action trong series “Tôi xem phim rác vì biết nó rác”.",
      stats: [86, 78, 76, 88, 86],
    },
    {
      id: "bm2", dept: "rv", orient: "h", yt: "KIZQjLPG2W8", views: 338856, hidden: true,
      title: "Batman Tuyệt Đối · Dragonball Evolution", client: "Kênh YouTube Batman Tuyệt Đối", year: "03/2026", duration: "17:13",
      role: "Dựng video review", tools: ["Premiere Pro", "After Effects"],
      panel: "Review Dragonball Evolution, tập 2 của series phim rác.",
      stats: [86, 78, 76, 88, 84],
    },
    {
      id: "bm3", dept: "rv", orient: "h", yt: "ZaaHaZ5XNK4", views: 290468, hidden: true,
      title: "Batman Tuyệt Đối · Madame Web", client: "Kênh YouTube Batman Tuyệt Đối", year: "02/2026", duration: "18:40",
      role: "Dựng video review", tools: ["Premiere Pro", "After Effects"],
      panel: "Review Madame Web, tập mở đầu series phim rác.",
      stats: [86, 78, 76, 88, 84],
    },
    {
      id: "bm4", dept: "rv", orient: "h", yt: "W25N1CYWN7g", views: 133952, hidden: true,
      title: "Batman Tuyệt Đối · One Piece live action 2", client: "Kênh YouTube Batman Tuyệt Đối", year: "03/2026", duration: "20:17",
      role: "Dựng video review", tools: ["Premiere Pro", "After Effects"],
      panel: "Review One Piece live action mùa 2.",
      stats: [86, 78, 76, 88, 84],
    },

    {
      id: "rx1", dept: "rv", orient: "h", featured: true,
      title: "Reaction · Clip vui trên mạng", client: "Kênh reaction", year: "01/2026", duration: "11:37",
      role: "Dựng video reaction", tools: ["Premiere Pro"],
      headline: "Một người xem, cả trăm clip viral",
      lead: "Video reaction dài 11 phút: người dẫn ngồi phản ứng bên cạnh từng clip viral, từ trò đùa trong nhà đến những pha bất ngờ của trẻ con và thú cưng.",
      sections: [
        { h: "Chia đôi khung hình", p: "Clip dọc đặt cạnh khuôn mặt người dẫn để người xem thấy cả tình huống lẫn phản ứng cùng lúc, cắt sát từng tiếng cười." },
        { h: "Nhịp dồn dập", p: "Phụ đề lớn, hiệu ứng tia tốc độ và âm thanh nhấn đúng khoảnh khắc, giữ nhịp nhanh cho một video dài." },
      ],
      panel: "Video reaction 11 phút: người dẫn phản ứng cạnh từng clip viral, phụ đề và hiệu ứng nhấn đúng khoảnh khắc buồn cười.",
      stats: [90, 72, 70, 86, 74],
    },
    /* ───────────── IV. SHORT VIDEO ───────────── */
    {
      id: "sv1", dept: "sv", orient: "v", featured: true,
      title: "QQ · Sơn Tinh Thủy Tinh", client: "QQ", year: "08/2026", duration: "0:43",
      role: "Dựng & VFX", tools: ["After Effects", "Premiere Pro"],
      headline: "Truyền thuyết trong 40 giây",
      lead: "Video dọc mang màu sắc thần thoại: dãy núi trong mây, người chiến binh và những tảng đá vỡ tung giữa trời.",
      sections: [
        { h: "Chất điện ảnh trên khung dọc", p: "Bố cục, ánh sáng và chuyển động máy được tính cho màn hình điện thoại. Hiệu ứng đá vỡ và bụi khói được ghép theo nhịp nhạc." },
        { h: "Âm thanh dẫn dắt", p: "Tiếng gió, tiếng đá và nhạc nền được đẩy dần lên cao trào để giữ người xem đến cuối." },
      ],
      panel: "Video dọc phong cách thần thoại: bố cục điện ảnh, VFX đá vỡ, âm thanh cao trào.",
      stats: [80, 90, 88, 88, 82],
    },
    {
      id: "sv9", dept: "sv", orient: "v", featured: true,
      title: "Lợi Trần · Con mèo đẻ 5 con", client: "Kênh YouTube Lợi Trần", year: "10/2026", duration: "0:43",
      role: "Dựng & animation", tools: ["After Effects", "Premiere Pro"],
      headline: "Một câu chuyện kể bằng hoạt hình trong 40 giây",
      lead: "Video ngắn hoạt hình cho kênh Lợi Trần: chú mèo đen có bầu, đẻ ra năm chú mèo con và một câu hỏi ngớ ngẩn về sáu cái núm vú.",
      sections: [
        { h: "Mỗi câu thoại một cảnh", p: "Phòng khách vẽ tay, màn hình gọi video, bông hoa khổng lồ và cảnh ghép mèo thật: bối cảnh đổi liên tục theo lời kể để giữ nhịp cho khung dọc." },
        { h: "Nhân vật có biểu cảm", p: "Nhân vật áo xanh và đàn mèo được diễn hoạt bằng biểu cảm phóng đại, phụ đề đặt giữa khung đúng vùng an toàn của Shorts và Reels." },
      ],
      panel: "Short hoạt hình 43 giây: bối cảnh vẽ tay đổi theo lời kể, diễn hoạt biểu cảm, ghép mèo thật.",
      stats: [88, 84, 90, 84, 90],
    },
    {
      id: "a4", dept: "sv", orient: "v",
      title: "Manzoku Izakaya · Spot", client: "Manzoku Izakaya", year: "07/2026", duration: "0:17",
      role: "Dựng & chữ động", tools: ["Premiere Pro", "After Effects"],
      panel: "Spot 17 giây cho quán izakaya: nhịp nhanh, chữ tiêu đề rõ, đúng vùng an toàn Reels.",
      stats: [95, 85, 70, 78, 72],
    },
    {
      id: "a5", dept: "sv", orient: "v",
      title: "KKokio · Reel", client: "KKokio", year: "07/2026", duration: "0:26",
      role: "Dựng & màu", tools: ["Premiere Pro", "DaVinci Resolve"],
      panel: "Reel gà rán: màu ấm, cắt theo tiếng giòn, nhấn vào texture món ăn.",
      stats: [85, 88, 55, 90, 70],
    },
    {
      id: "sv4", dept: "sv", orient: "v",
      title: "Onbeat · Âm thanh chữa lành", client: "Onbeat", year: "06/2026", duration: "0:51",
      role: "Dựng", tools: ["Premiere Pro"],
      panel: "Review quán nướng: tiếng nướng xèo xèo, tiêu đề lớn, nhịp vui.",
      stats: [82, 84, 50, 92, 74],
    },
    {
      id: "sv5", dept: "sv", orient: "v",
      title: "Onbeat · Quán nướng Hàn", client: "Onbeat", year: "05/2026", duration: "1:15",
      role: "Dựng & chữ động", tools: ["Premiere Pro", "After Effects"],
      panel: "Giới thiệu quán nướng Hàn Quốc: không gian, menu set và trải nghiệm.",
      stats: [80, 82, 62, 80, 80],
    },
    {
      id: "b6", dept: "sv", orient: "v",
      title: "IMUNDEX · Tủ áo nâng hạ", client: "IMUNDEX", year: "09/2026", duration: "0:29",
      role: "Dựng & phụ đề", tools: ["Premiere Pro", "After Effects"],
      panel: "Reel sản phẩm nội thất, thuộc series hơn 100 video. Cận cơ cấu, phụ đề tiếng Anh.",
      stats: [80, 84, 60, 72, 75],
    },
    {
      id: "sv7", dept: "sv", orient: "v",
      title: "IMUNDEX · Walk-in closet", client: "IMUNDEX", year: "07/2026", duration: "0:58",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      panel: "Giới thiệu phòng thay đồ: chuyển động mượt, ánh sáng ấm, phụ đề tiếng Anh.",
      stats: [76, 86, 58, 74, 78],
    },

    /* ───────────── VIII. NEWS & TRAVEL ───────────── */
    {
      id: "c1", dept: "nw", orient: "v", featured: true,
      title: "VTV8 · Vietnam Travel — Huế", client: "VTV8", year: "09/2026", duration: "1:02",
      role: "Dựng", tools: ["Premiere Pro", "After Effects"],
      headline: "Huế trong một phút",
      lead: "Đại Nội nhìn từ trên cao, phá Tam Giang lúc hoàng hôn, chiếc thuyền nhỏ trên mặt nước phẳng lặng. Một tập trong series Vietnam Travel của VTV8.",
      sections: [
        { h: "Nhịp chậm cho một vùng đất chậm", p: "Chọn những khung hình đẹp nhất, để mỗi cảnh đủ thời gian, nhạc nền nhẹ và phụ đề tiếng Anh ngắn gọn." },
        { h: "Một series đều tay", p: "Khung nhận diện của kênh giữ nguyên qua hàng chục tập: Cát Bà, Sa Pa, Ninh Bình, Đà Lạt, Cô Tô, Quy Nhơn…" },
      ],
      panel: "Series du lịch VTV8: nhịp chậm, cảnh đẹp, khung nhận diện kênh nhất quán.",
      stats: [65, 90, 55, 78, 82],
    },
    {
      id: "c2", dept: "nw", orient: "v",
      title: "Vietnam Travel — Đèo Hải Vân", client: "VTV8", year: "09/2026", duration: "1:12",
      role: "Dựng", tools: ["Premiere Pro"],
      panel: "Flycam liền mạch dọc cung đèo, kể chuyện theo hành trình.",
      stats: [68, 88, 50, 75, 80],
    },
    {
      id: "nw5", dept: "nw", orient: "v",
      title: "Vietnam News — 5 mẹo đi xe mùa ngập", client: "VTV8", year: "10/2026", duration: "0:56",
      role: "Dựng & đồ hoạ", tools: ["Premiere Pro", "After Effects"],
      panel: "Tin dạng danh sách: 5 mẹo an toàn khi đi xe qua đường ngập, đánh số rõ ràng.",
      stats: [84, 72, 62, 70, 84],
    },

    /* ───────────── VII. FOOD REVIEW ───────────── */
    {
      id: "c3", dept: "fd", orient: "v", featured: true,
      title: "VTC Foodie — 4 nét Huế", client: "VTC", year: "10/2026", duration: "2:08",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      headline: "Bốn món Huế giữa lòng Hà Nội",
      lead: "Hai bạn trẻ dẫn khán giả đi ăn bốn món Huế. Show ẩm thực dọc với nhịp vui, phụ đề rõ và những cú cận món ăn khiến người xem muốn lưu địa chỉ.",
      sections: [
        { h: "Giữ phản ứng thật", p: "Giữ lại khoảnh khắc người dẫn nếm thử, cắt bỏ phần thừa, chèn cận món đúng lúc nhắc tên." },
        { h: "Phụ đề gọn trong khung dọc", p: "Phụ đề và tiêu đề đặt trong vùng an toàn, đọc được cả khi xem không bật tiếng." },
      ],
      panel: "Show ẩm thực dọc cho VTC: dẫn chuyện tự nhiên, phụ đề, cận món ăn.",
      stats: [80, 78, 50, 75, 86],
    },
    {
      id: "fd2", dept: "fd", orient: "v", featured: true,
      title: "VTC Foodie — Tôm hùm", client: "VTC", year: "09/2026", duration: "3:08",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      headline: "Bữa tôm hùm ba người",
      lead: "Ba người dẫn cùng thưởng thức tôm hùm, vừa ăn vừa trò chuyện. Tập dài hơn ba phút nhưng nhịp vẫn nhanh và vui.",
      sections: [
        { h: "Dựng hội thoại nhiều người", p: "Chuyển góc máy theo người nói, giữ các câu đùa và phản ứng để không khí bữa ăn tự nhiên." },
        { h: "Món ăn là nhân vật chính", p: "Cận cảnh lúc bóc vỏ, chấm sốt, cắn miếng đầu tiên. Màu được chỉnh để món ăn trông tươi và hấp dẫn." },
      ],
      panel: "Tập dài 3 phút: hội thoại nhiều người dẫn, cận món ăn, nhịp vui.",
      stats: [78, 82, 48, 76, 84],
    },
    {
      id: "fd3", dept: "fd", orient: "v",
      title: "VTC Foodie — Ốc", client: "VTC", year: "10/2026", duration: "3:12",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      panel: "Đi ăn ốc vỉa hè: tiêu đề vui, phản ứng thật, cận món.",
      stats: [80, 76, 52, 74, 84],
    },
    {
      id: "fd4", dept: "fd", orient: "v",
      title: "VTC Foodie — Hoa ốc Hải Phòng", client: "VTC", year: "09/2026", duration: "3:32",
      role: "Dựng & phụ đề", tools: ["Premiere Pro"],
      panel: "Tập Hải Phòng: ốc, cháo và lời bình của người dẫn.",
      stats: [76, 80, 48, 72, 82],
    },
    {
      id: "fd5", dept: "fd", orient: "v",
      title: "VTC Foodie — Recap", client: "VTC", year: "07/2026", duration: "0:50",
      role: "Dựng", tools: ["Premiere Pro"],
      panel: "Recap ngắn các tập: nhiều người dẫn, nhiều món, nhịp nhanh.",
      stats: [90, 80, 55, 78, 76],
    },

    /* ───────────── V. BRAND FILM ───────────── */
    {
      id: "bt1", dept: "br", orient: "h", featured: true,
      title: "Nút giao Hòa Xuân · Phim dự án 3D", client: "DaPixel Agency", year: "08/2026", duration: "3:24",
      role: "Dựng phim & đồ hoạ chú thích", tools: ["Premiere Pro", "After Effects"],
      headline: "Một nút giao mới cho thành phố của những cây cầu",
      lead: "Phim giới thiệu dự án hạ tầng cụm nút giao Lê Thanh Nghị – Cách Mạng Tháng Tám – Thăng Long và đường dẫn lên cầu Hòa Xuân, Đà Nẵng. Xuất bản 4K.",
      sections: [
        { h: "Từ flycam đến mô phỏng 3D", p: "Mở đầu bằng hoàng hôn và nhịp sống Đà Nẵng về đêm, rồi chuyển vào mô phỏng 3D từng hạng mục: hầm chui, cầu vượt, hướng rẽ của từng làn xe." },
        { h: "Đồ hoạ dẫn đường", p: "Chú thích tên tuyến, hướng đi và thông số kỹ thuật xuất hiện đúng lúc camera lướt qua, để người xem không chuyên vẫn hiểu dự án." },
      ],
      panel: "Phim dự án hạ tầng 4K: flycam Đà Nẵng, mô phỏng 3D nút giao, đồ hoạ chú thích từng hạng mục.",
      stats: [80, 86, 84, 78, 88],
    },
    {
      id: "b1", dept: "br", orient: "v", featured: true,
      title: "Regal · Teaser Nguyễn Hùng", client: "Regal Group", year: "04/2026", duration: "0:50",
      role: "Dựng & motion", tools: ["Premiere Pro", "After Effects"],
      headline: "Teaser công bố nghệ sĩ",
      lead: "Teaser công bố ca sĩ Nguyễn Hùng cho đêm nhạc tại Regal Fountain. Hình ảnh điện ảnh, ngôi sao vàng rực và biển người phía dưới.",
      sections: [
        { h: "Dựng như trailer", p: "Mở màn bằng cận cảnh kịch tính, giữa phim là logo sự kiện bùng sáng, kết bằng tên nghệ sĩ giữa đám đông. Xuất bản 4K dọc." },
        { h: "Một trong ba dạng video cho Regal", p: "Teaser sự kiện, video KOL review và phim sản phẩm, cùng một hệ màu và nhận diện." },
      ],
      panel: "Teaser công bố nghệ sĩ 4K: nhịp trailer, logo bùng sáng, đám đông cao trào.",
      stats: [86, 90, 88, 88, 82],
    },
    {
      id: "b4", dept: "br", orient: "h", featured: true,
      title: "Regal × Kohler · Chuẩn quốc tế", client: "Regal Group × Kohler", year: "06/2026", duration: "1:48",
      role: "Dựng & màu", tools: ["Premiere Pro", "DaVinci Resolve"],
      headline: "Phim sản phẩm trong căn hộ mẫu",
      lead: "Phòng tắm xanh ngọc, bồn tắm chân đồng, vòi sen ba chế độ. Phim giới thiệu thiết bị Kohler bên trong căn hộ Regal.",
      sections: [
        { h: "Chậm và sạch", p: "Chuyển động chậm, nhiều khoảng thở, chữ serif mảnh. Một số đoạn chuyển sang đen trắng để làm nổi chất liệu kim loại và nước." },
        { h: "Chi tiết tạo cảm giác cao cấp", p: "Cận cảnh bề mặt, giọt nước và ánh sáng, đúng tinh thần một thương hiệu thiết bị cao cấp." },
      ],
      panel: "Phim sản phẩm 16:9: nhịp chậm, chất liệu, đen trắng điện ảnh.",
      stats: [60, 95, 65, 85, 80],
    },
    {
      id: "b5", dept: "br", orient: "h", featured: true,
      title: "Mizuki Park · Trellia Cove", client: "Mizuki Park", year: "06/2026", duration: "1:48",
      role: "Dựng & tracking 3D", tools: ["After Effects", "Premiere Pro"],
      headline: "Bản đồ dự án nhìn từ trên cao",
      lead: "Flycam bay qua công viên, dòng sông và các toà T1, T2, T3. Đường viền phát sáng và nhãn chữ bám theo địa hình như một tấm bản đồ sống.",
      sections: [
        { h: "Tracking 3D từng khung hình", p: "Camera tracking để đường viền và nhãn luôn dính vào công trình khi máy bay di chuyển. Người xem hiểu ngay vị trí và tiện ích." },
        { h: "Dành cho bất động sản", p: "Phù hợp để giới thiệu quy hoạch, kết nối và tiến độ của khu đô thị hay khu nghỉ dưỡng." },
      ],
      panel: "Highlight flycam với camera tracking 3D: đường viền sáng, nhãn bám địa hình.",
      stats: [70, 82, 92, 70, 80],
    },
    {
      id: "br2", dept: "br", orient: "v",
      title: "Regal · KOL review", client: "Regal Group", year: "04/2026", duration: "1:56",
      role: "Dựng & chữ động", tools: ["Premiere Pro", "After Effects"],
      panel: "Video KOL giới thiệu dự án: lời dẫn, flycam, tiêu đề nhấn ý chính.",
      stats: [80, 86, 70, 78, 84],
    },
    {
      id: "br5", dept: "br", orient: "h",
      title: "Bravo · TVC Vĩnh Hưng", client: "Bravo", year: "04/2026", duration: "1:33",
      role: "Dựng", tools: ["Premiere Pro", "After Effects"],
      panel: "TVC bất động sản: phối cảnh đời sống, kết nối hạ tầng, nhịp nhẹ nhàng.",
      stats: [72, 86, 74, 78, 80],
    },
    {
      id: "br6", dept: "br", orient: "h",
      title: "Focus · TVC Queen Kara", client: "Focus Event", year: "06/2024", duration: "2:36",
      role: "Dựng & màu", tools: ["Premiere Pro", "After Effects"],
      panel: "TVC karaoke 4K có kịch bản hài: tình huống, nhân vật, combo giá và hotline.",
      stats: [84, 86, 70, 84, 86],
    },

    /* ───────────── VI. LED VISUAL ───────────── */
    {
      id: "led4", dept: "led", orient: "v", ratio: "1376/1080", featured: true,
      title: "QQ · Visual Cô Đôi Thượng Ngàn", client: "QQ", year: "07/2026", duration: "6:29",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      headline: "Cổng trăng, đàn nguyệt và những cánh quạt",
      lead: "Visual sân khấu sáu phút rưỡi tông ngọc bích: cổng trăng giữa núi mây, cây đàn nguyệt trên mặt nước, những chiếc quạt giấy xoè rộng và ngôi đình phát sáng.",
      sections: [
        { h: "Chất liệu văn hoá Việt", p: "Hoạ tiết mây, hoa sen, đàn nguyệt và mái đình được dựng thành một không gian huyền ảo, đi cùng tiết mục mang âm hưởng dân gian." },
        { h: "Chuyển cảnh theo nhạc", p: "Mỗi đoạn bài hát là một cảnh, ánh sáng và vật thể chuyển động theo nhịp để sân khấu luôn sống." },
      ],
      panel: "Visual sân khấu 6 phút tông ngọc bích: cổng trăng, đàn nguyệt, quạt giấy, chuyển cảnh theo nhạc.",
      stats: [70, 96, 92, 86, 84],
    },
    {
      // Mứt Gừng gom thành một trang: video chính d1, hai bài còn lại (gallery) xem ngay trên trang
      id: "d1", dept: "led", orient: "h", ratio: "2800/1300", featured: true, gallery: ["d2", "led3"],
      title: "Mứt Gừng · Bộ visual đêm nhạc", client: "Mứt Gừng", year: "09/2025", duration: "3:54",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      headline: "Một đêm nhạc, mỗi bài hát một thế giới",
      lead: "Bộ visual cho màn LED chính 2800×1300 của đêm nhạc Mứt Gừng: đại dương mặt trời hồng, thành phố neon synthwave và một bản ballad màu dịu.",
      sections: [
        { h: "Chạy theo từng bài hát", p: "Minh hoạ phẳng, chuyển động khớp lời và nhịp trống. Nhịp hình chậm ở verse, mở rộng ở điệp khúc, phần chính nằm giữa màn để mọi góc khán phòng đều nhìn rõ." },
      ],
      panel: "Bộ visual màn LED chính 2800×1300 cho đêm nhạc Mứt Gừng: đại dương, thành phố neon, ballad.",
      stats: [65, 92, 86, 86, 76],
    },
    {
      id: "d2", dept: "led", orient: "h", ratio: "2800/1300", hidden: true,
      title: "Mứt Gừng · Đừng dừng lại", client: "Mứt Gừng", year: "09/2025", duration: "4:06",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      panel: "Visual synthwave cho màn LED chính: cánh cổng neon, ánh sáng theo nhịp trống.",
      stats: [78, 90, 85, 88, 65],
    },
    {
      id: "led3", dept: "led", orient: "h", ratio: "2800/1300", hidden: true,
      title: "Mứt Gừng · Trái tim bên lề", client: "Mứt Gừng", year: "09/2025", duration: "5:54",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      panel: "Visual ballad cho màn LED chính, nhịp hình theo cảm xúc bài hát.",
      stats: [55, 88, 80, 84, 80],
    },
    {
      id: "ocb", dept: "led", orient: "h",
      title: "OCB · Visual sân khấu", client: "OCB", year: "06/2024", duration: "6:10",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      panel: "Visual màn LED cho sự kiện OCB: cánh đồng lúa, dải lụa đỏ, chim công và kaleidoscope nhiều màu.",
      stats: [70, 94, 88, 80, 70],
    },
    {
      id: "vt24", dept: "led", orient: "h", ratio: "3996/1080",
      title: "Vietravel 2024 · Visual toàn sân khấu", client: "Vietravel", year: "11/2024", duration: "8:13",
      role: "Thiết kế & motion visual", tools: ["After Effects", "Photoshop"],
      panel: "Visual toàn sân khấu siêu rộng cho Vietravel 2024: đồi chè, bầu trời mây, kaleidoscope ánh sáng.",
      stats: [72, 90, 86, 82, 74],
    },
  ],

  // Khách hàng — kiểu chữ: display | gothic | serif
  clients: [
    { name: "Lợi Trần", note: "Kênh YouTube", style: "display" },
    { name: "VTV8 Expats", note: "Truyền hình VTV8", style: "gothic" },
    { name: "Foodie Vietnam", note: "Thuộc VTC", style: "serif" },
    { name: "Regal Group", note: "Bất động sản", style: "display" },
    { name: "Kohler", note: "Thiết bị cao cấp", style: "serif" },
    { name: "Mizuki Park", note: "Bất động sản", style: "gothic" },
    { name: "Bravo", note: "Truyền thông", style: "display" },
    { name: "IMUNDEX", note: "Nội thất", style: "gothic" },
    { name: "Onbeat", note: "Agency", style: "serif" },
    { name: "QQ", note: "Nghệ sĩ", style: "display" },
    { name: "Manzoku", note: "Nhà hàng", style: "serif" },
    { name: "KKokio", note: "Nhà hàng", style: "gothic" },
    { name: "Vui Vẻ", note: "Kênh YouTube", style: "display" },
    { name: "Teakill", note: "Kênh YouTube", style: "gothic" },
    { name: "Batman Tuyệt Đối", note: "Kênh YouTube", style: "serif" },
    { name: "Sofa TV", note: "Kênh bóng đá", style: "display" },
    { name: "Focus Event", note: "Sự kiện · Karaoke", style: "serif" },
    { name: "Nghịch", note: "Vlog", style: "display" },
    { name: "N2L Entertainment", note: "Sản xuất nội dung", style: "serif" },
    { name: "Wemo Media", note: "Hoạt hình", style: "gothic" },
    { name: "FPT University", note: "Giáo dục", style: "display" },
    { name: "Mứt Gừng", note: "Đêm nhạc", style: "serif" },
    { name: "OCB", note: "Ngân hàng", style: "gothic" },
    { name: "Vietravel", note: "Du lịch", style: "display" },
  ],
};
